In [1]:
import pandas as pd

In [3]:
FAF_path = r'C:\Users\nataliabrown\Documents\5 - Projects\Freight Model Update\FAF5.4.1\FAF5.4.1.csv'

In [5]:
dfFAF = pd.read_csv(FAF_path)
display(dfFAF)

,fr_orig,dms_orig,dms_dest,fr_dest,fr_inmode,dms_mode,fr_outmode,sctg2,trade_type,dist_band,...,tmiles_2019,tmiles_2020,tmiles_2022,tmiles_2023,tmiles_2025,tmiles_2030,tmiles_2035,tmiles_2040,tmiles_2045,tmiles_2050
0,NaN,11,11,NaN,NaN,1,NaN,1,1,1,...,3.351765,3.375547,3.614785,3.718716,4.364371,5.327137,6.342501,7.763605,9.571647,11.343818
1,NaN,11,19,NaN,NaN,1,NaN,1,1,2,...,50.646235,51.005589,54.030117,55.009693,62.052488,72.493059,82.113979,96.869428,116.602924,134.683927
2,NaN,11,129,NaN,NaN,1,NaN,1,1,3,...,0.468714,0.472040,0.483170,0.481371,0.486727,0.533539,0.564126,0.638719,0.750361,0.844720
3,NaN,11,131,NaN,NaN,1,NaN,1,1,2,...,2.267241,2.283328,2.359789,2.352784,2.549854,3.018065,3.155784,3.394250,3.850035,4.178881
4,NaN,11,139,NaN,NaN,1,NaN,1,1,2,...,1.327792,1.337213,1.412938,1.412791,1.554450,1.863748,1.969298,2.141527,2.456208,2.683008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269412,NaN,559,61,808.0,NaN,1,3.0,43,3,8,...,0.000000,0.000000,0.266742,0.275206,0.294010,0.345016,0.396155,0.457549,0.531255,0.619805
2269413,NaN,559,171,808.0,NaN,1,4.0,43,3,2,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2269414,NaN,559,279,808.0,NaN,7,7.0,43,3,3,...,0.000000,0.000000,1.837802,1.883146,1.995468,2.270674,2.560981,2.905823,3.315489,3.802593
2269415,NaN,559,512,808.0,NaN,1,3.0,43,3,6,...,0.000000,0.000000,0.000511,0.000535,0.000578,0.000698,0.000818,0.000963,0.001139,0.001350
2269416,NaN,560,151,808.0,NaN,7,7.0,43,3,8,...,0.000000,0.000000,21.876334,22.482755,23.813470,27.408215,31.135441,35.549942,40.781738,46.988840